name: Release Latest

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete old release if exists
        run: |
          gh release delete latest -y || true
          git push origin :refs/tags/latest || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create zip archive
        run: |
          zip -r assets.zip ./* \
            -x "*.git*" \
            -x ".idea*"

      - name: Create new Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: assets.zip
          draft: false
          prerelease: false
