name: Build and Upload

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact (clean)
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: ./
          exclude: |
            **/.git*
            **/.idea*
